config/routes.rb
Events::Application.routes.draw do
  resources :events do
    post 'check_email', on: :collection
    post 'checkin', on: :collection
  end

  post '/charge' => 'charges#new_charge'

  root :to => "pages#index"

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  attr_accessible :event_id, :volunteer_id

  belongs_to :event
  belongs_to :volunteer
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :location, :start_time, :end_time

  has_many :checkins
end

app/models/list.rb
class List < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/location.rb
class Location < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :terms_agreed, :wants_to_join_mailing_list

  has_many :checkins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new_charge

    token = params[:stripeToken]
    amount = params[:chargeAmount]
    centAmount = amount.to_i
    description = params[:chargeDesc]

    Stripe.api_key = STRIPE_SECRET

    # Create a customer to check address_line1, address_zip, and cvc for
    # legitimacy before charging.
    customer = Stripe::Customer.create(
      :card => token,
      :email => description,
    )

    if customer.active_card.address_line1_check == "fail"
      @error = "Address check failed."
    elsif customer.active_card.address_zip_check == "fail"
      @error = "Address check failed."
    elsif customer.active_card.cvc_check == "fail"
      @error = "CVC check failed."
    else
      charge = Stripe::Charge.create(
        :amount => centAmount, # amount in cents, again
        :currency => "usd",
        :customer => customer,
        :description => description
      )
    end

    rescue Stripe::CardError => e
      @error = e.message + '.'
      render "/pages/fail", layout: 'pages'
      return
    rescue Stripe::InvalidRequestError => e
      @error = e.message + '.'
      render "/pages/fail", layout: 'pages'
      return
    rescue Stripe::AuthenticationError => e
      @error = e.message + '.'
      render "/pages/fail", layout: 'pages'
      return
    rescue Stripe::APIConnectionError => e
      @error = e.message + '.'
      render "/pages/fail", layout: 'pages'
      return
    rescue Stripe::StripeError => e
      @error = e.message + '.'
      render "/pages/fail", layout: 'pages'
      return
    rescue => e
      @error = e.message + '.'
      render "/pages/fail", layout: 'pages'
      return
    else 
      render "/pages/success", layout: 'pages'
    end
    

end

app/controllers/events_controller.rb
require 'net/http'

class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @checkins = Checkin.find_all_by_event_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def check_email
    email = params['email']
    event = params['event'].to_i
    vol = Volunteer.find_by_email(email)    
    key = MAILCHIMP_API_KEY
    baseurl = "https://us6.api.mailchimp.com/2.0/lists/member-info.json"

    if !vol.nil?
      fname = vol.first_name
      lname = vol.last_name
      email = vol.email
      terms = true
      if !Checkin.where('event_id = ? and volunteer_id = ?', event, vol.id).empty?
        # HTTP 208 being "already reported"
        status = 208
      end
    else
      req = Net::HTTP::Post.new(baseurl)
      req.set_form_data('apikey' => key, 'id' => "e565ef60d3",
        "emails[0][email]" => email)

      http = Net::HTTP.new(URI.parse(baseurl).host, '443')
      http.use_ssl = true
      http.start do |http|
        res = http.request(req)
        body = res.body
        memberinfo = JSON.parse(body)
        if (memberinfo['success_count'] > 0)
          fname = memberinfo['data'][0]['merges']['FNAME']
          lname = memberinfo['data'][0]['merges']['LNAME']
          terms = false
        else
          fname = lname = ''
          terms = false
        end
      end
    end
    render :json => {:fname => fname, :lname => lname, :email => email,
      :terms => terms}, :status => (status ? status : 200)
  end

  def checkin
    email = params['email']
    fname = params['fname']
    lname = params['lname']
    event = params['event'].to_i
    join = params['ml_signup'] ? params['ml_signup'] : false
   
    vol = Volunteer.find_by_email(email)

    if vol.nil?
      vol = Volunteer.new(email: email, first_name: fname, last_name: lname,
        terms_agreed: true, wants_to_join_mailing_list: join)
      vol.save!
    end

    ci = Checkin.new(event_id: event, volunteer_id: vol.id)
    ci.save!

    # return good status, vol id, time for updating form.

    render :json => {:name => "#{fname} #{lname}", 
      :checkin_time => ci.created_at.strftime("%B %e, %I:%M %p")} 
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    render 'index', layout: 'pages'
  end
  def success 
    render 'success', layout: 'pages'
  end
  def fail
    render 'fail', layout: 'pages'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
<%= form_for @event, html:{role:'form'} do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :name, "Event name" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class='form-group'>
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  
  <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
</div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class='container'>
<h1>Upcoming events</h1>

<table class='table table-bordered'>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th colspan=4>Actions</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.location %></td>
    <td><%= link_to 'Check In', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<div class="container">

<h1>Create new event</h1>

<hr>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

</div>

app/views/events/show.html.erb
<div class="container">
<div class='row'>
<p id="notice"><%= notice %></p>
<h1><%= @event.name %></h1>
<h4>@ <%= @event.location %></h4>
<hr>
<div id="vol_message" style="display:none;"></div>
<h3>Volunteer Check In</h3>

<form role='form' id='vol_checkin_form'>
  <input id='checkin_event' type='hidden' name='event' value="<%= @event.id %>">
  
  <div class='form-group'>
    <label for='checkin_email'>Your Email Address</label>
    <input id='checkin_email' class='form-control' name='email' type='email'>
  </div>

  <div class='row'>
    <div class='col-md-6'>
      <div class='form-group'>
        <label for='checkin_fname'>First Name</label>
        <input id='checkin_fname' class='form-control' name='fname'>
      </div>
    </div>
    <div class='col-md-6'>
      <div class='form-group'>
        <label for='checkin_lname'>Last Name</label>
        <input id='checkin_lname' class='form-control' name='lname'>
      </div>
    </div>
  </div>

  <div class='row' id='vol_checkin_terms' style="display:none;">
    <div class='col-md-8'>
      <h4>Just to make sure we're on the same page...</h4>
      By checking in, you agree to:
      <ul>
        <li>Not sue Concrete Jungle</li>
        <li>Not do stupid things</li>
        <li>Come back soon</li>
      </ul>
    </div>
  </div>

  <div class="row" id="vol_checkin_ml" style="display:none;">
    <div class='col-md-8'>
      <label class='checkbox'>
        <input type="checkbox" id='ml_signup_check' name="ml_signup"> Subscribe me to Concrete Jungle's mailing list too.
      </label>
    </div>
  </div>

  <button id='vol_checkin_btn' class="btn btn-lg btn-primary btn-block" type="submit" disabled>Check In</button>
</form>

<hr>

<h3>Already Checked In</h3>

<table class='table table-bordered'>
  <tr id='header'>
    <th>Name</th>
    <th>Time</th>
  </tr>

  <% @checkins.reverse_each do |c| %>
  <% vol = Volunteer.find(c.volunteer_id) %>
  <tr>
    <td><%= vol.first_name %> <%= vol.last_name %></td>
    <td><%= c.created_at.strftime("%B %e, %I:%M %p") %></td>
  </tr>
  <% end %>
</table>


</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Events</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <%= javascript_include_tag "bootstrap" %>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Donate to Concrete Jungle</title>
  <%= stylesheet_link_tag "pages" %>
  <%= stylesheet_link_tag "stripe" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
    <%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script type="text/javascript" src="https://checkout.stripe.com/v2/checkout.js"></script>
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <%= javascript_include_tag "bootstrap" %>
</body>
</html>

app/views/pages/_blurb.html.erb
<p>First of all, thank you for even considering donating to Concrete Jungle &#8212; we are entirely volunteer-run and our expenses are things that contribute directly to hungry people getting fresh food: IKEA bags for hauling apples and pears, farm tools, drip irrigation supplies, irrigation bills, etc. </p>
<p>We operate on a very small budget and are efficient with the resources we have. In 2013 Concrete Jungle:
<ul>
<li>Donated over 4,700 lbs of fresh produce (more fruit and more trees than in any previous year)</li>
<li>Greatly improved our farm that we started in 2012, and produced 400+ lbs of fruit at greatly reduced effort on our part.
</ul>
</p>
<p>We are growing in many fun directions and have several new projects planned for 2014 to connect Atlantans with the bounty that surrounds them in new and fun ways. We would be very grateful to receive your donation towards making those projects a reality.</p>
<p>
We have also recently formed a relationship with <a href="http://www.georgiaorganics.org">Georgia Organics</a> where they will be acting as fiscal agent for Concrete Jungle. If you are interested in making a <strong>tax-deductible donation</strong> to Concrete Jungle, it will need to be done through them. Please <a href="mailto:info@concrete-jungle.org">get in touch</a> and we can assist you.
</p>
<p>Thank you!<br />
Craig Durkin<br />
Plant Manager, Concrete Jungle</p>
<hr>
<%= render partial: "checkout" %>

app/views/pages/_checkout.html.erb
<div class="inputholder">
<div class="amount">
  <label for="checkoutAmount">Donation amount ($USD, $1.00 minimum)</label>
  <input id="checkoutAmount" type='number' min="1" max="1000" required><br/>
<button class="stripe-button-el"><span>Donate</span></button>
</div>
<div class="policy">
All data are provided for the sole purpose of authenticating the donation with our credit card gateway. No data are stored on Concrete Jungle's servers, and all credit card details (name, card number, expiration date, cvc, address) are securely transmitted directly to the credit card gateway without passing through Concrete Jungle's servers.
</div>
</div>


<script>
    $('.stripe-button-el').click(function() {
      var token = function(res) {
        $('.stripe-button-el').attr("disabled", "disabled");

        $.post('/charge', {
          stripeToken: res.id,
          chargeAmount: amount,
          chargeDesc: donationEmail,
          },
          function(data) {
            $(".entry").html(data);
          });
       }

      var donationEmail = $("#donationEmail").val();
      var amount = Math.floor(($('#checkoutAmount').val() * 100));
      if (amount < 100) {
        $('#checkoutAmount').css("border-color", "#ff0000");
        $('#checkoutAmount').css("outline", "none");
        $('#checkoutAmount').css("-moz-box-shadow", "inset 0 1px 2px rgba(70,123,181,0.35), 0 0 4px #ff0000");
        $('#checkoutAmount').css("-webit-box-shadow", "inset 0 1px 2px rgba(70,123,181,0.35), 0 0 4px #ff0000");
        $('#checkoutAmount').css("box-shadow", "inset 0 1px 2px rgba(70,123,181,0.35), 0 0 4px #ff0000");
        return false;
      } else {
        StripeCheckout.open({
          key:         '<%= STRIPE_PUBLIC %>',
          address:     true,
          name:        'Concrete Jungle',
          panelLabel:  'Checkout',
          token:       token,
          image:       "http://www.concrete-jungle.org/wp-content/themes/green-apples/images/cjsmall.jpg",
        });


        return false;
      }
    });
</script>

app/views/pages/_fail.html.erb
Sorry, the donation could not be completed: <%= @error %>
<p/>
Please try again.
<br />
<%= render partial: 'checkout' %>

app/views/pages/_header.html.erb
<div class="navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li> 
           <a href="http://www.concrete-jungle.org/" style="padding:0;">
            <img src="http://www.concrete-jungle.org/wp-content/themes/green-apples/images/logo.png">
           </a> 
        </li>
        <li class='dropdown'>
          <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/about"> About Concrete Jungle</a> 
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li> <a role="menuitem" href="/about">About</a> </li>
            <li> <a role="menuitem" href="/contact">Contact</a> </li>
          </ul>
        </li>
        <li> <a href="/?page_id=103">Food Map</a> </li>
        <li> <a href="/?page_id=510">Fruits of Atlanta</a> </li>
        <li> <a href="/dog-head-farms">Dog Head Farm</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/pages/_success.html.erb
Thank you for your donation! It is very much appreciated. If you have any issue with your donation, do not hesitate to <a href="http://www.concrete-jungle.org/?page_id=717">drop us a line</a> and we'll get it sorted out.
<p/>
<a href="http://www.concrete-jungle.org">Back to Concrete Jungle</a>

app/views/pages/fail.html.erb
          Sorry, the donation could not be completed: <%= @error %>
          <p/>
          Please try again.
          <br />
          <%= render partial: 'pages/checkout' %>

app/views/pages/index.html.erb
<%= render partial: 'pages/header' %>

<div class="row rowpadding">
  <div class="container">
    <div class="col-md-8 content shadow">
      <h2>Donate to Concrete Jungle</h2>
      <div class="post" id="post-cjdonate">
        <div class="entry">
          <%= render partial: "pages/blurb" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clear whitespace"> </div>
<div id="footer">
<p />
&#169;2014 Concrete Jungle <img class="centered" src="http://www.concrete-jungle.org/wp-content/themes/green-apples/images/email.png" alt="" />
</div>

</body>
</html>

app/views/pages/success.html.erb
          Thank you for your donation! It is very much appreciated. If you have any issue with your donation, do not hesitate to <a href="http://www.concrete-jungle.org/?page_id=717">drop us a line</a> and we'll get it sorted out.
<p/>
<a href="http://www.concrete-jungle.org">Back to Concrete Jungle</a>